name: Deploy Bot

# Trigger deployment on push to main or manual workflow_dispatch
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: write
  id-token: write
  actions: write
  repository-projects: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt
        pip install -r bot/requirements-prod.txt

    - name: Create deployment packages
      run: |
        # Create dist directory
        mkdir -p dist/temp

        # Main bot function
        echo "Creating main bot function package..."
        cp bot/main.py dist/temp/
        cp bot/requirements.txt dist/temp/
        cp -r bot/utils dist/temp/
        cd dist/temp
        zip -r ../bot-source.zip .
        cd ../..

        # Firestore function
        echo "Creating Firestore function package..."
        rm -rf dist/temp/*
        cp bot/firestore_function.py dist/temp/main.py
        cp bot/requirements-prod.txt dist/temp/requirements.txt
        cd dist/temp
        zip -r ../firestore-function.zip .
        cd ../..

        # Webhook function
        echo "Creating webhook function package..."
        rm -rf dist/temp/*
        cp bot/webhook_check_function.py dist/temp/main.py
        cp bot/requirements-prod.txt dist/temp/requirements.txt
        cd dist/temp
        zip -r ../webhook-function.zip .
        cd ../..

        # Clean up
        rm -rf dist/temp

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/github-actions-pool-prod/providers/github-actions-provider-prod'
        service_account: 'github-deployer@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
        create_credentials_file: true
        export_environment_variables: true

    - name: Deploy Infrastructure
      run: |
        cd terraform
        terraform init
        terraform plan
        terraform apply -auto-approve

    - name: Log Deployment
      run: |
        echo "Deployment completed at $(date)" >> deployment.log
        echo "Environment: ${{ github.event.inputs.environment || 'dev' }}" >> deployment.log
        echo "Source version: ${{ github.sha }}" >> deployment.log
        echo "Bot source zip: bot-source.zip" >> deployment.log
        echo "Firestore function zip: firestore-function.zip" >> deployment.log
        echo "Webhook function zip: webhook-function.zip" >> deployment.log